### PR TITLE
[Project A][Linux][drustanyjt] Upgrade to Java 17

### PR DESCRIPTION
**Pull request by drustanyjt**
Slightly modified the gradle build properties. These were not necessary to get the build to work.

**OS:** Ubuntu 22.04.4 LTS
**JDK:** OpenJDK
**IDE:** IntelliJ IDEA Ultimate 2024.1.4
**JAR file:** https://github.com/drustanyjt/AB3-J17/releases/tag/v0.3

### CODE REVIEW

**Comment by itstrueitstrueitsrealitsreal** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

### Steps followed:
1. Downloaded the JAR file from the PR.
2. Switched to JDK-FX 17.0.11.fx-zulu using SDKMAN.
3. Ran the JAR file using `java -jar Ubuntu22-drustanyjt.jar`.
4. Performed a smoke test to verify basic functionality.

### Results:
Everything is functioning as expected.

### Screenshots:

Screenshot 2024-07-04 at 4 36 23 PM

**Comment by jyue487** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps and results are identical to above.

**Comment by teoks0199** [comment]
Tested on Windows 11, and working.

Steps followed:

1. Downloaded the JAR file from the PR.
2. Ran the JAR file using java -jar Ubuntu22-drustanyjt.jar.
3. Performed a smoke test to verify basic functionality.

image

**Comment by macareonie** [comment]
Tested on Windows 11 with Oracle OpenJDK version 17.0.11, and working.

image

**Comment by bennyLCK** [comment]
Smoke-Tested on Windows 11, using Oracle OpenJDK version 17.0.10 on Windows Powershell Terminal running the `java -jar Ubuntu22-drustanyjt.jar` command, basic commands were run to ensure full functionality of the application.

image

**Comment by baskargopinath** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps followed:
Downloaded the JAR file from the PR.
Switched to JDK-FX 17.0.11.fx-zulu
Ran the JAR file using java -jar Ubuntu22-drustanyjt.jar.
Performed a smoke test to verify basic functionality.
Results:
Everything is functioning as expected.

Screenshots:
image

**Comment by aureliony** [comment]
Tested on Ubuntu 22.04.4 LTS with zulu jdk 17.0.11. JAR is working fine.

Steps followed:
Downloaded the JAR file from the release.
Ran the JAR file using `java -jar Ubuntu22-drustanyjt.jar`.
Performed a smoke test to check basic functionality.

Results:
Everything is functioning as expected.
Screenshot from 2024-07-06 19-35-13

**Comment by gongg21** [comment]
Tested on **MacSilicon** with JDK-FX 17.0.11.fx-zulu, and working fine.
Switched using SDKMAN, ensure it is **17.0.11.fx-zulu**, note the `.fx` suffix.
Add/Delete command tested, works.
Help command tested, works.
Ran JAR file using `java -jar <filename>`.

Screenshot 2024-07-07 at 5 44 19 PM

**Comment by Carlintyj** [comment]
Tested on Mac (Silicon) using JDK-FX 17.0.11.fx-zulu and working.

Downloaded the JAR release, ran the jar file using java -jar Ubuntu22-drustanyjt.jar
Performed smoke test to check functionality.

Screenshot 2024-07-07 at 7 25 44 PM

**Comment by brein62** [comment]
Tested on **Windows 10** using JDK-FX 17.0.11.fx-zulu, and working.

## Procedure

Ran the JAR file on PowerShell using `java -jar Ubuntu22-drustanyjt.jar` and performed a smoke test by running several commands to ensure basic functionality of the application:

- `add n/John p/12345678 e/johnd@example.com a/123 Example Road t/friends`: works
- `find Roy`: works
- `list`: works
- `help`: works
- `delete 3`: works
- `clear`: works

## Results
The JAR functions as expected and all commands run during the smoke test work properly.

## Screenshots
Ubuntu22-drustanyjt

**Comment by jedkohjk** [comment]
Tested on Windows 11 and working.

Steps I followed:
1. Downloaded the JAR file from the release.
2. Ran `java -jar Ubuntu22-drustanyjt.jar`.
3. Tested some basic commands.

Screenshot

**Comment by damithc** [comment]
Closing, as the migration was done in https://github.com/nus-oss/AB3-J17/commit/fe805d8553bbc329644371a6e732a8317ea6686f

**Pull request closed without merging**
