### PR TITLE
Update UG to say ‘latest jar’ instead of addressbook.jar

### LINKED ISSUE #23: Update UG to say ‘latest jar’ instead of specific file name
Context:
image

If we make this step generic (e.g., `... latest .jar file from ...`) without specifying the exact file name, it doesn't need to be updated every time a new release is done.

### PR DESCRIPTION
**Pull request by brein62**
Fixes #23. Changes `UserGuide.md` by replacing "latest `addressbook.jar`" with "latest `.jar` file":

```diff
- 1. Download the latest `addressbook.jar` from [here](https://github.com/se-edu/addressbook-level3/releases).
+ 1. Download the latest `.jar` file from [here](https://github.com/se-edu/addressbook-level3/releases).

```

### CODE REVIEW

**Review by drustanyjt — APPROVED** [review]
LGTM

**Comment by damithc** [comment]
@brein62 can you provide a commit message body too?

Follow the guidelines given in https://se-education.org/guides/conventions/git.html

**Comment by jyue487** [comment]
LGTM.

I have another suggestion. Is it okay if we directly include the jar file link itself, meaning clicking on the link will automatically download the.jar file instead of redirecting them to the release page first, it could ease the users more as one working step is reduced, but we will have to ensure the link is correct and valid every time we make updates to the jar file.

**Comment by brein62** [comment]
> LGTM.
> 
> I have another suggestion. Is it okay if we directly include the jar file link itself, meaning clicking on the link will automatically download the.jar file instead of redirecting them to the release page first, it could ease the users more as one working step is reduced, but we will have to ensure the link is correct and valid every time we make updates to the jar file.

@jyue487 This is a good idea from a user standpoint. However, this would not improve developers' workflows when a release is published since they would still have to update the link to reflect the newest release of the JAR file.

Since #23 aims to reduce the additional workload of developers having to update the UG to reflect the new name of the JAR file with each new release, this suggestion might not be a great improvement compared to what we have previously.

**Comment by drustanyjt** [comment]
> will have to ensure the link is correct and valid every time we make updates to the jar file.

@jyue487 I think this would add more inconvenience (from having to remember to change 1 extra link) than effort saved. Maybe it could be changed to link to the latest release by using "https://github.com/se-edu/addressbook-level3/releases/latest" instead? This way the link doesn't need to be changed every release, but still directs the user to the correct .jar file to download.

Personally I prefer leaving it as is now because it gives students an opportunity to get familiar with the GitHub releases page as a whole.

**Comment by aureliony** [comment]
Personally, I recommend linking the releases/latest page as suggested by @drustanyjt. As this is for the UG (not DG), having multiple jar files on the same page might confuse users that are not familiar with GitHub. It depends on the project's target audience. Ideally, the link should lead to a download page on the project's own website, not GitHub, but this is not possible for tp.

**Comment by damithc** [comment]
Thanks for the PR @brein62 and others for the inputs.
For now, let's merge this as is (except a few column width adjustments to the commit message).

**Pull request merged**
