### PR TITLE
[Project A][MacIntel][Kenneth Seet] Upgrade to Java 17 

### PR DESCRIPTION
**Pull request by damithc**
This is based on https://github.com/nus-oss/AB3-J17/pull/6 (by @itstrueitstrueitsrealitsreal) but using a **Mac Intel** computer to generate the JAR file.

JDK used: 17.0.11.fx-zulu
JAR file https://github.com/nus-oss/AB3-J17/releases/download/v0.3.0/MacIntel-KennethSeet.jar

### CODE REVIEW

**Comment by itstrueitstrueitsrealitsreal** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

### Steps followed:
1. Downloaded the JAR file from the PR.
2. Switched to JDK-FX 17.0.11.fx-zulu using SDKMAN.
3. Ran the JAR file using `java -jar MacIntel-KennethSeet.jar`.
4. Performed a smoke test to verify basic functionality.

### Results:
Everything is functioning as expected.

### Screenshots:
Screenshot 2024-07-04 at 4 28 41 PM

**Comment by jyue487** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps and results are identical to above.

**Comment by teoks0199** [comment]
Tested on Windows 11, and working.

Steps I followed:

1. Downloaded the JAR file from the PR.
2. Ran the JAR file using java -jar MacIntel-KennethSeet.jar.
3. Performed a smoke test to check basic functionality.

image

**Comment by bennyLCK** [comment]
Smoke-Tested on Windows 11, using Oracle OpenJDK version 17.0.10 on Windows Powershell Terminal same as @teoks0199, basic commands were run to ensure full functionality of the application.

image

**Comment by baskargopinath** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps I followed:

Downloaded the JAR file from the PR.
Switched to JDK-FX 17.0.11.fx-zulu 
Ran the JAR file using java -jar MacIntel-KennethSeet.jar.
Performed a smoke test to check basic functionality.
Results:
Everything is functioning as expected.

Screenshots:
image

**Comment by aureliony** [comment]
Tested on Ubuntu 22.04.4 LTS with zulu jdk 17.0.11. JAR is working fine.

Steps followed:
Downloaded the JAR file from the release.
Ran the JAR file using `java -jar MacIntel-KennethSeet.jar`.
Performed a smoke test to check basic functionality.

Results:
Everything is functioning as expected.

Screenshot from 2024-07-06 19-31-00

**Comment by gongg21** [comment]
Tested on **MacSilicon** with JDK-FX 17.0.11.fx-zulu, and working fine.
Switched using SDKMAN, ensure it is **17.0.11.fx-zulu**, note the `.fx` suffix.
Add/Delete command tested, works.
Help command tested, works.
Ran JAR file using `java -jar <filename>`.

Screenshot 2024-07-07 at 5 36 22 PM

**Comment by Carlintyj** [comment]
Tested on Mac (Silicon) using JDK-FX 17.0.11.fx-zulu and working.

Downloaded the JAR release, ran the jar file using java -jar MacIntel-KennethSeet.jar
Performed smoke test to check functionality.

Screenshot 2024-07-07 at 7 14 57 PM

**Comment by drustanyjt** [comment]
Tested on Linux (Ubuntu 22.04) using OpenJDK 17.0.11. Working.

Steps taken:

1. Downloaded release
2. Ran jar file using `java -jar MacIntel-KennethSeet.jar`
3. Tested with basic commands

image

**Comment by brein62** [comment]
Tested on **Windows 10** using JDK-FX 17.0.11.fx-zulu, and working.

## Procedure

Ran the JAR file on PowerShell using `java -jar MacIntel-KennethSeet.jar` and performed a smoke test by running several commands to ensure basic functionality of the application:

- `add n/John p/12345678 e/johnd@example.com a/123 Example Road t/friends`: works
- `find Roy`: works
- `list`: works
- `help`: works
- `delete 3`: works
- `clear`: works

## Results
The JAR functions as expected and all commands run during the smoke test work properly.

## Screenshots
MacIntel-KennethSeet

**Comment by jedkohjk** [comment]
Tested on Windows 11 and working.

Steps I followed:
1. Downloaded the JAR file from the release.
2. Ran `java -jar MacIntel-KennethSeet.jar`.
3. Tested some basic commands.

Screenshot

**Comment by damithc** [comment]
Closing, as the migration was done in https://github.com/nus-oss/AB3-J17/commit/fe805d8553bbc329644371a6e732a8317ea6686f

**Pull request closed without merging**
