### PR TITLE
AboutUs.md: Change http -> https

### LINKED ISSUE #25: AboutUs.md: Change http -> https
As per https://github.com/nus-cs2103-AY2324S2/forum/issues/850

### PR DESCRIPTION
**Pull request by hjungwoo01**
Fixes #25

### CODE REVIEW

**Comment by damithc** [comment]
Suggested commit message subject `AboutUs.md: Change http -> https`

**Comment by damithc** [comment]
> Suggested commit message subject `AboutUs.md: Change http -> https`

@hjungwoo01 this suggestion was for the commit message, not the PR

**Comment by hjungwoo01** [comment]
> > Suggested commit message subject `AboutUs.md: Change http -> https`
> 
> @hjungwoo01 this suggestion was for the commit message, not the PR

Oh I see, I have made the appropriate changes.

**Comment by damithc** [comment]
Thanks for the PR, @hjungwoo01

**Pull request merged**
