### PR TITLE
[Project A][Win10, Linux][aureliony] Upgrade to Java 17

### PR DESCRIPTION
**Pull request by aureliony**
**OS**: Windows 10, Ubuntu 22.04.4 LTS
**JDK Distribution**: Azul Zulu
**IDE used**: IntelliJ IDEA Community Edition
**Link to JAR files**: https://github.com/aureliony/AB3-J17/releases

No problems were faced on Windows 10 and Ubuntu (dual-boot). Unable to test on Mac.

### CODE REVIEW

**Comment by damithc** [comment]
@aureliony Can you upload a version generated on Linux as well?

**Comment by aureliony** [comment]
Release page updated to include JAR file generated on Ubuntu 22.04.4 LTS with Zulu JDK 17.0.11.

**Comment by Carlintyj** [comment]
Tested on Mac (Silicon) using JDK-FX 17.0.11.fx-zulu and working.

Downloaded the JAR release, ran the jar file using java -jar Linux-aureliony.jar
Performed smoke test to check functionality.

Screenshot 2024-07-07 at 7 30 50 PM

**Comment by brein62** [comment]
Tested on **Windows 10** using JDK-FX 17.0.11.fx-zulu, and working.

## Procedure

Ran the JAR files (Linux/Ubuntu and Windows 10) on PowerShell using `java -jar Linux-aureliony.jar` and `java -jar Win10-aureliony.jar` respectively and performed a smoke test by running several commands to ensure basic functionality of the application:

- `add n/John p/12345678 e/johnd@example.com a/123 Example Road t/friends`: works for both
- `find Roy`: works for both
- `list`: works for both
- `help`: works for both
- `delete 3`: works for both
- `clear`: works for both

## Results
Both JARs function as expected and all commands run during the smoke test work properly for both JAR files created on Linux and Windows.

## Screenshots
### Linux JAR
Linux-aureliony

### Windows JAR
Win10-aureliony

**Comment by drustanyjt** [comment]
Tested on Linux (Ubuntu 22.04) using OpenJDK 17.0.11. Working.

Steps taken:

1. Downloaded release
2. Ran jar file using `java -jar Linux-aureliony.jar`
3. Tested with basic commands

image

**Comment by jedkohjk** [comment]
Tested both jar files on Windows 11 and working.

Steps I followed:
1. Downloaded the JAR file from the release.
2. Ran `java -jar Linux-aureliony.jar`.
3. Tested some basic commands.
4. Closed the program.
5. Ran `java -jar Win10-aureliony.jar`.
6. Tested some basic commands.

Screenshot

Screenshot

**Comment by damithc** [comment]
Closing, as the migration was done in https://github.com/nus-oss/AB3-J17/commit/fe805d8553bbc329644371a6e732a8317ea6686f

**Pull request closed without merging**
