### PR TITLE
[Project A][Win11][BennyLoh] Upgrade to Java 17

### PR DESCRIPTION
**Pull request by bennyLCK**
Only the minimal changes were made to the AB3 codebase and the JAR file works as per normal after the minor changes.

OS: Windows 11
JDK used: Oracle OpenJDK version 17.0.10
IDE used: IntelliJ Ultimate Edition
Link to uploaded JAR file: [Win11-BennyLoh](https://github.com/bennyLCK/AB3-J17/releases/tag/v0.1)

### CODE REVIEW

**Comment by itstrueitstrueitsrealitsreal** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

### Steps followed:
1. Downloaded the JAR file from the PR.
2. Switched to JDK-FX 17.0.11.fx-zulu using SDKMAN.
3. Ran the JAR file using `java -jar Win11-BennyLoh.jar`.
4. Performed a smoke test to verify basic functionality.

### Results:
Everything is functioning as expected.

### Screenshots:
Screenshot 2024-07-04 at 4 40 11 PM

**Comment by jyue487** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps and results are identical to above.

**Comment by teoks0199** [comment]
Tested on Windows 11, and working.

Steps followed:

1. Downloaded the JAR file from the PR.
2. Ran the JAR file using java -jar Win11-BennyLoh.jar.
3. Performed a smoke test to verify basic functionality.

image

**Comment by baskargopinath** [comment]
Tested on Mac Silicon with JDK-FX 17.0.11.fx-zulu, and working.

Steps followed:
Downloaded the JAR file from the PR.
Switched to JDK-FX 17.0.11.fx-zulu using SDKMAN.
Ran the JAR file using java -jar Win11-BennyLoh.jar.
Performed a smoke test to verify basic functionality.
Results:
Everything is functioning as expected.

Screenshots:
image

**Comment by aureliony** [comment]
Tested on Ubuntu 22.04.4 LTS with zulu jdk 17.0.11. JAR is working fine.

Steps followed:
Downloaded the JAR file from the release.
Ran the JAR file using `java -jar Win11-BennyLoh.jar`.
Performed a smoke test to check basic functionality.

Results:
Everything is functioning as expected.
Screenshot from 2024-07-06 19-36-45

**Comment by gongg21** [comment]
Tested on **MacSilicon** with JDK-FX 17.0.11.fx-zulu, and working fine.
Switched using SDKMAN, ensure it is **17.0.11.fx-zulu**, note the `.fx` suffix.
Add/Delete command tested, works.
Help command tested, works.
Ran JAR file using `java -jar <filename>`.

Screenshot 2024-07-07 at 5 41 12 PM

**Comment by Carlintyj** [comment]
Tested on Mac (Silicon) using JDK-FX 17.0.11.fx-zulu and working.

Downloaded the JAR release, ran the jar file using java -jar Win11-BennyLoh.jar
Performed smoke test to check functionality.

Screenshot 2024-07-07 at 7 23 22 PM

**Comment by drustanyjt** [comment]
Tested on Linux (Ubuntu 22.04) using OpenJDK 17.0.11. Working.

Steps taken:

1. Downloaded release
2. Ran jar file using `java -jar Win11-BennyLoh.jar`
3. Tested with basic commands

image

**Comment by jedkohjk** [comment]
Tested on Windows 11 and working.

Steps I followed:
1. Downloaded the JAR file from the release.
2. Ran `java -jar Win11-BennyLoh.jar`.
3. Tested some basic commands.

Screenshot

**Comment by damithc** [comment]
Closing, as the migration was done in https://github.com/nus-oss/AB3-J17/commit/fe805d8553bbc329644371a6e732a8317ea6686f

**Pull request closed without merging**
