### PR TITLE
Remove AB3 tutorials

### LINKED ISSUE #22: Remove AB3 tutorials
As they have been moved to https://se-education.org/guides/tutorials/ab3.html, they can be removed from this codebase

### PR DESCRIPTION
**Pull request by teoks0199**
Closes #22.

### CODE REVIEW

**Comment by damithc** [comment]
@teoks0199 Check if image files need to be removed as well.
When writing the commit message, follow the guidelines given in https://se-education.org/guides/conventions/git.html

**Review by brein62 — COMMENTED** [review]
Going through the three deleted pages, the images that are no longer needed are all nicely organised and located in folders:
- `./docs/images/add-remark`
- `./docs/images/remove`
- `./docs/images/tracing`

There are several other images used in `TracingCode.md` but not located in `./docs/images/tracing`. These are still used in the DG and cannot be deleted.

**Comment by teoks0199** [comment]
Thanks @brein62 for identifying the images to be deleted, these images are indeed not used elsewhere. Prof @damithc, is it okay to remove all 26 png files located in those folders in one single commit?

**Comment by damithc** [comment]
> Thanks @brein62 for identifying the images to be deleted, these images are indeed not used elsewhere. Prof @damithc, is it okay to remove all 26 png files located in those folders in one single commit?

@teoks0199 Sure. In fact, the whole PR should be just one commit.

**Review by damithc — CHANGES_REQUESTED** [review]
@teoks0199 the commit message body exceeds the max width.
The description can be quite brief (i.e., as the tutorial has been moved to ..., let's remove it from here).

**Comment by damithc** [comment]
@teoks0199 Thanks for the PR. FYI, I shortened the commit message further.

**Pull request merged**
