### PR TITLE
Revert TLS workaround after upgrading to JDK17

### LINKED ISSUE #18: Reverse Java-11 specific workaround in gradle.properties
See if we can reverse this now ...

https://github.com/se-edu/addressbook-level3/commit/09837d98cc0443a75e7291e6aceb76764e18ca04

### PR DESCRIPTION
**Pull request by aureliony**
Closes #18

### CODE REVIEW

**Comment by hjungwoo01** [comment]
I followed what was changed in this PR and after testing, I can confirm that everything works as expected. There were no issues with GitHub Actions, and both Java CI and Codecov are functioning correctly on my Mac Silicon.

**Comment by baskargopinath** [comment]
works on m2 macbook pro, sonoma 14.5. @damithc, im wondering if we should test on macOS sequoia beta which will be released in september. so if mid-semester if some students upgrade to it we might be better prepared

**Comment by damithc** [comment]
> works on m2 macbook pro, sonoma 14.5. @damithc, im wondering if we should test on macOS sequoia beta which will be released in september. so if mid-semester if some students upgrade to it we might be better prepared

Yes @baskargopinath , in general, it's a good idea to test on upcoming version if feasible.

**Comment by damithc** [comment]
@aureliony Can you add a detailed commit message (subject + body) too?

Follow the guidelines given in https://se-education.org/guides/conventions/git.html

**Pull request merged**
